### ISSUE TITLE
Add/Edit page in svelte

### ISSUE THREAD

**Issue by FrolickingMustelid** [Hack-Weekly/crimson-eagle-notes-app#4]
Markdown editor: https://github.com/bytedance/bytemd
might be buggy with sveltekit: https://www.reddit.com/r/sveltejs/comments/12axr97/good_markdown_editor_for_sveltekit/

Another editor, in case the first one doesn't work out: https://github.com/ssssota/svelte-exmarkdown

**Comment by Pfreym** [comment]
added Milkdown Editor after researching a few ideas including bytemd and monaco

**Comment by Pfreym** [comment]
closing as we are going for raw text with a live preview
