### ISSUE TITLE
Note behaviour 

### ISSUE THREAD

**Issue by Pfreym** [Hack-Weekly/crimson-eagle-notes-app#6]
Decide on how our note component would behave. Do our maximum characters fill the element?

I think our note should be able to be longer. Would it expand on click? In a seperate page or window?
Expand on hover?

**Comment by FrolickingMustelid** [comment]
We need a full sized, scrollable view/edit page unless the notes are limited to a very small size. We can have a "summary" in frontmatter that shows on the note thumbnails, or just use the first paragraph/x letters of the note.

**Comment by Pfreym** [comment]
Yeh I agree an extra editing screen would be great. Possibly with more "tools"
